accountapp/urls.py
from django.urls import path
from accountapp.views import AccountDeleteView, hello_world, AccountCreateView, AccountDetailView, AccountUpdateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


# django의 무시무시한 form class 상속!!! 미리 다 만들어져 있다!!
class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from accountapp.models import HelloWorld


has_ownership = [login_required, account_ownership_required]

# Create your views here.

@login_required
def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={
            'hello_world_list': hello_world_list
        })

## 미쳤다. user creation. 단순성. 와.........
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Sign Up</h4>
  </div>
  <form action="{% url 'accountapp:create' %}" method="post">
    {% csrf_token %}
    <!--  -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Quit</h4>
  </div>
  <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
    {% csrf_token %}
    <!--  -->
    <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html'%}

<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <p>{{ target_user.date_joined }}</p>

    {% if target_user.profile %}
    <img
      src="{{ target_user.profile.image.url }}"
      alt=""
      style="
        height: 10rem;
        width: 10rem;
        border-radius: 10rem;
        margin-bottom: 2rem;
      "
    />
    <h2 style="font-family: NanumSquareNeoB">
      {{ target_user.profile.nickname }}
      <!--  -->
      {% if user == target_user %}
      <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">edit</a>
      {% endif %}
      <!--  -->
    </h2>
    <h5>{{ target_user.profile.message }}</h5>
    {% else %}
    <h4>
      <!--  -->
      {% if user == target_user %}
      <a href="{% url 'profileapp:create' %}">Create Profile</a>
      {% else %}
      <h4>닉네임 미설정</h4>
      {% endif %}
      <!--  -->
    </h4>
    {% endif %}
  </div>

  {% if user == target_user %}
  <div>
    <a href="{% url 'accountapp:update' pk=user.pk %}">
      <button class="btn btn-dark rounded-pill col-6 mt-3">Change Info</button>
    </a>
  </div>
  <div>
    <a href="{% url 'accountapp:delete' pk=user.pk %}">
      <button class="btn btn-dark rounded-pill col-6 mt-3">Quit</button>
    </a>
  </div>

  {% endif %}
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}
<!--  -->

{% block content %}

<div style="border-radius: 1rem; margin: 2rem; text-align: center">
  <h1 style="font-family: 'Lobster', cursive">Hello, world LIST!</h1>

  <form action="/account/hello_world/" method="post">
    {% csrf_token %}
    <div>
      <input type="text" name="hello_world_input" />
    </div>
    <div>
      <input type="submit" class="btn btn-primary" value="POST" />
    </div>
  </form>

  {% if hello_world_output %}
  <h1>{{ hello_world_output.text }}</h1>
  {% endif %}
  <!--  -->
  {% if hello_world_list %}
  <div>
    <h1>글 목록</h1>
    <ul>
      {% for hello_world in hello_world_list %}
      <li>{{ hello_world.text }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
</div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4>Login</h4>
  </div>
  <form action="" method="post">
    {% csrf_token %}
    <!--  -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Change Info</h4>
  </div>
  <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
    {% csrf_token %}
    <!--  -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}