accountapp/urls.py
from django.urls import path
from accountapp.views import AccountDeleteView, hello_world, AccountCreateView, AccountDetailView, AccountUpdateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path
from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = "projectapp"

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include 'head.html' %}

  <body style="font-family: NanumSquareNeoR">
    {% include 'header.html' %}

    <!--  -->
    <hr />

    {% block content %}{% endblock %}

    <!--  -->
    <hr />

    {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<div class="pragmatic_footer">
  <div class="pragmatic_footer_button">
    <span>공지사항</span> | <span>제휴문의</span> |
    <span>서비스소개</span>
  </div>
  <div style="margin-top: 1rem">
    <h6 class="pragmatic_footer_logo">Pragmatic</h6>
  </div>
</div>

templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
  />
  <title>Pragmatic</title>

  <!-- Bootrstrap -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    crossorigin="anonymous"
  />
  <!-- 구글폰트 -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Lobster&family=Roboto&display=swap"
    rel="stylesheet"
  />

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'base.css' %}" />

  <!-- Fonts -->
  <style>
    @font-face {
      font-family: "NanumSquareNeoE";
      src: url("{% static 'fonts/NanumSquareNeoOTF-Eb.otf' %}")
        format("opentype");
    }
    @font-face {
      font-family: "NanumSquareNeoB";
      src: url("{% static 'fonts/NanumSquareNeoOTF-Bd.otf' %}")
        format("opentype");
    }
    @font-face {
      font-family: "NanumSquareNeoR";
      src: url("{% static 'fonts/NanumSquareNeoOTF-Rg.otf' %}")
        format("opentype");
    }
    @font-face {
      font-family: "NanumSquareNeoL";
      src: url("{% static 'fonts/NanumSquareNeoOTF-Lt.otf' %}")
        format("opentype");
    }
    @font-face {
      font-family: "NanumSquareNeoH";
      src: url("{% static 'fonts/NanumSquareNeoOTF-Hv.otf' %}")
        format("opentype");
    }
  </style>
</head>

templates/header.html
<div class="pragmatic_header">
  <div>
    <h1 class="pragmatic_header_logo">Pragmatic</h1>
  </div>
  <div>
    <a href="{% url 'articleapp:list' %}">Articles</a>
    <a href="{% url 'projectapp:list' %}">Projects</a>
    <span>Nav 1</span>
    <span>Nav 2</span>
    <span>Nav 3</span>
    <span>Nav 4</span>
    {% if not user.is_authenticated %}
    <a href="{% url 'accountapp:login' %}?next={{request.path}}">
      <span>Login</span>
    </a>
    <a href="{% url 'accountapp:create' %}?next={{request.path}}">
      <span>SignUp</span>
    </a>
    {% else %}
    <a href="{% url 'accountapp:detail' pk=user.pk %}">
      <span>MyPage</span>
    </a>
    <a href="{% url 'accountapp:logout' %}?next={{request.path}}">
      <span>Logout</span>
    </a>
    {% endif %}
  </div>
</div>