articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article

class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

articleapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy

from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from articleapp.decorators import article_ownership_required
from articleapp.models import Article
from articleapp.forms import ArticleCreationForm
from django.views.generic.edit import FormMixin
from commentapp.forms import CommentCreationForm


# Create your views here.
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'
    
    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('articleapp:list')
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'
    
class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 5
    ordering = ['-created_at']

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Article Create</h4>
  </div>
  <form
    action="{% url 'articleapp:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <!--  -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Delete Article: {{ target_article.title }}</h4>
  </div>
  <form
    action="{% url 'articleapp:delete' pk=target_article.pk %}"
    method="post"
  >
    {% csrf_token %}
    <!--  -->
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html'%}

<!--  -->
{% block content %}

<div style="text-align: center; max-width: 700px; margin: 4rem auto">
  <h1>{{ target_article.title }}</h1>
  <h4>{{ target_article.writer.profile.nickname }}</h4>
  <h5>{{ target_article.created_at }}</h5>
  <hr />
  <img
    style="width: 100%; border-radius: 1rem; margin: 2rem 0"
    src="{{ target_article.image.url }}"
    alt=""
  />
  <p>{{ target_article.content }}</p>

  {% if user == target_article.writer %}
  <div>
    <a href="{% url 'articleapp:update' pk=target_article.pk %}">
      <button class="btn btn-dark rounded-pill col-4 mt-3">Edit</button>
    </a>
  </div>
  <div>
    <a href="{% url 'articleapp:delete' pk=target_article.pk %}">
      <button class="btn btn-dark rounded-pill col-4 mt-3">Delete</button>
    </a>
  </div>
  {% endif %}
  <hr />
  {% for comment in target_article.comment.all %}
  <!--  -->
  {% include 'commentapp/detail.html' with comment=comment %}
  <!--  -->
  {% endfor %}
  <!--  -->
  {% include 'commentapp/create.html' with article=target_article %}
  <!--  -->
</div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html'%} {% load static %}

<!--  -->
{% block content %}

<style>
  .container {
    margin: 0 auto;
    padding: 0;
  }
  .container div {
    background-color: antiquewhite;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 1rem;
  }

  .container img {
    width: 100%;
    border-radius: 1rem;
  }

  .container a {
    width: 40%;
    max-width: 250px;
  }
</style>

{% if article_list %}
<div class="container">
  {% for article in article_list %}
  <a href="{% url 'articleapp:detail' pk=article.pk %}">
    <!--  -->
    {% include 'snippets/card.html' with article=article %}
  </a>
  {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div class="text-center">
  <h4>No Articles</h4>
</div>
{% endif %}
<!--  -->
{% include 'snippets/pagination.html' with page_obj=page_obj %}

<div style="text-align: center">
  <a
    href="{% url 'articleapp:create' %}"
    class="btn btn-dark rounded-pill col-3 mt-3 mb-3"
    >Create Article</a
  >
</div>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
<!--  -->
{% load bootstrap4%}
<!--  -->
{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4 class="mb-4">Article Update</h4>
  </div>
  <form
    action="{% url 'articleapp:update' pk=target_article.pk %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <!--  -->
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" />
  </form>
</div>

{% endblock %}